global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Métricas da sua API .NET (Oficina)
  - job_name: 'oficina-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:80']

  # Métricas do próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Host Linux (CPU, memória, disco, etc. via node-exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Containers Docker (CPU/memória por container via cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Se (e só se) você tiver um OTEL Collector rodando
  # - job_name: 'otel-collector'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['otel-collector:4318']
